// Copyright 2024 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_THERMAL_THERMAL_ZONES_TEST_DTS_THERMAL_ZONES_TEST_H_
#define LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_THERMAL_THERMAL_ZONES_TEST_DTS_THERMAL_ZONES_TEST_H_

#define CRITICAL_TEMP 101200

#endif  // LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_THERMAL_THERMAL_ZONES_TEST_DTS_THERMAL_ZONES_TEST_H_
