// Copyright 2023 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_REGULATOR_REGULATOR_TEST_DTS_REGULATOR_TEST_H_
#define LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_REGULATOR_REGULATOR_TEST_DTS_REGULATOR_TEST_H_

#define REGULATOR_NAME "cpu0-regulator"
#define MIN_VOLTAGE 790000
#define MAX_VOLTAGE 1100000
#define STEP_VOLTAGE 1000

#endif  // LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_REGULATOR_REGULATOR_TEST_DTS_REGULATOR_TEST_H_
