// Copyright 2024 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef LIB_DRIVER_DEVICETREE_VISITORS_DEFAULT_BOOT_METADATA_TEST_DTS_BOOT_METADATA_TEST_H_
#define LIB_DRIVER_DEVICETREE_VISITORS_DEFAULT_BOOT_METADATA_TEST_DTS_BOOT_METADATA_TEST_H_

#define TEST_ZBI_TYPE1 0x4D425355
#define TEST_ZBI_EXTRA1 0

#define TEST_ZBI_TYPE2 11
#define TEST_ZBI_EXTRA2 4

#endif  // LIB_DRIVER_DEVICETREE_VISITORS_DEFAULT_BOOT_METADATA_TEST_DTS_BOOT_METADATA_TEST_H_
