// Copyright 2024 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_USB_AML_USB_PHY_TEST_DTS_AML_USB_PHY_TEST_H_
#define LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_USB_AML_USB_PHY_TEST_DTS_AML_USB_PHY_TEST_H_

#define PLL_SETTING_1 0x100
#define PLL_SETTING_2 0x101
#define PLL_SETTING_3 0x100000
#define PLL_SETTING_4 0x200
#define PLL_SETTING_5 0xFFFF0000
#define PLL_SETTING_6 0x10
#define PLL_SETTING_7 0x1
#define PLL_SETTING_8 0x50060

#endif  // LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_USB_AML_USB_PHY_TEST_DTS_AML_USB_PHY_TEST_H_
