// Copyright 2024 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_USB_DWC2_TEST_DTS_DWC2_TEST_H_
#define LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_USB_DWC2_TEST_DTS_DWC2_TEST_H_

#define TEST_G_RX_FIFO_SIZE 256
#define TEST_G_NP_TX_FIFO_SIZE 36
#define TEST_G_TX_FIFO_SIZE_0 128
#define TEST_G_TX_FIFO_SIZE_1 8
#define TEST_G_TURNAROUND_TIME 9
#define TEST_DMA_BURST_LENGTH 512

#endif  // LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_USB_DWC2_TEST_DTS_DWC2_TEST_H_
