#!/bin/bash
# Copyright 2020 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Build
### manage distributed compilation client (deprecated)

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../lib/vars.sh || exit $?

set -euo pipefail

cat <<EOF
Goma is no longer supported.  'fx goma' does nothing.

To remote build C++ using reclient on RBE,
you can 'fx set --cxx-rbe' or equivalently,
set 'cxx_rbe_enable = true' in args.gn.

EOF
