// Copyright 2023 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_SYSMEM_TEST_DTS_SYSMEM_TEST_H_
#define LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_SYSMEM_TEST_DTS_SYSMEM_TEST_H_

#define TEST_PID 0x20
#define TEST_VID 0x30
#define TEST_CONTIGUOUS_SIZE 1100000
#define TEST_PROTECTED_SIZE 200000

#endif  // LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_SYSMEM_TEST_DTS_SYSMEM_TEST_H_
