// Copyright 2024 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_DISPLAY_DISPLAY_PANEL_TEST_DTS_DISPLAY_PANEL_TEST_H_
#define LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_DISPLAY_DISPLAY_PANEL_TEST_DTS_DISPLAY_PANEL_TEST_H_

#define TEST_PANEL_TYPE 0x12
#define TEST_DISPLAY_WIDTH 1920
#define TEST_DISPLAY_HEIGHT 1080

#endif  // LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_DISPLAY_DISPLAY_PANEL_TEST_DTS_DISPLAY_PANEL_TEST_H_
