rules = { SOI ~ EOF* ~ ASM ~ EOF* ~ ( RESULT | ERROR ) ~ EOF* ~ EOI }

WHITESPACE = _{ " " }
_COMMENT   = _{ "#" ~ (!NEWLINE ~ ANY)* ~ NEWLINE }
EOF = _{ NEWLINE | _COMMENT }

HEXPREFIX = _{ "0x" }
HEXSUFFIX = { ASCII_HEX_DIGIT+ }
HEXNUM = _{ HEXPREFIX ~ HEXSUFFIX }
DECNUM = @{ ASCII_DIGIT+ }
NUM = { HEXNUM | DECNUM }
SIGN = { "+" | "-" }
IMM = { SIGN? ~ NUM }
OFFSET = { SIGN ~ NUM }
EXIT = { "exit" }

REG_PREFIX = _{ "%r" }
REG_NUMBER = { ASCII_DIGIT{1, 2} }
REG = _{ REG_PREFIX ~ REG_NUMBER }
DEREF = { "[" ~ REG ~ OFFSET? ~ "]" }

BASE_BINARY_OP = @{ "add" | "sub" | "mul" | "div" | "or" | "and" | "lsh" | "rsh" | "mod" |
                    "xor" | "mov" | "arsh" }
BINARY_OP = @{ BASE_BINARY_OP ~ ( "32" )? }
UNARY_OP = @{ ( "neg" ~ ( "32" )? ) | "le16" | "le32" | "le64" | "be16" | "be32" | "be64" }

ALU_INSTRUCTION = { ( UNARY_OP ~ REG ) |
                    ( BINARY_OP  ~ REG ~ "," ~ (REG | IMM) ) }

STORE_REG_OP = @{ "stxb" | "stxh" | "stxw" | "stxdw" }
STORE_IMM_OP = @{ "stb" | "sth" | "stw" | "stdw" }
LOAD_OP = @{ "ldxb" | "ldxh" | "ldxw" | "ldxdw" }

MEM_INSTRUCTION = { ( STORE_REG_OP ~ DEREF ~ "," ~ REG ) |
                    ( STORE_IMM_OP ~ DEREF ~ "," ~ IMM ) |
                    ( LOAD_OP ~ REG ~ "," ~ DEREF ) |
                    ( "lddw" ~ REG ~ "," ~ IMM ) }

BASE_JMP_OP = @{ "jeq" | "jgt" | "jge" | "jlt" | "jle" | "jset" | "jne" | "jsgt" |
                 "jsge" | "jslt" | "jsle" }
JMP_OP = @{ BASE_JMP_OP ~ ( "32" )? }

JMP_CONDITIONAL = { JMP_OP ~ REG ~ "," ~ (REG | IMM) ~ "," ~ ( OFFSET | EXIT ) }
JMP = { "ja" ~ OFFSET }
CALL = { "call" ~ IMM }
JMP_INSTRUCTION = { JMP_CONDITIONAL |
                    JMP |
                    CALL |
                    EXIT }

ASM_INSTRUCTION = { (   ALU_INSTRUCTION |
                        MEM_INSTRUCTION |
                        JMP_INSTRUCTION |
                        ""
                    ) ~ EOF }

ASM = { "-- asm" ~ EOF ~
        ASM_INSTRUCTION+ }

RESULT = { "-- result" ~ EOF ~
           IMM ~  EOF }

ERROR =  { "-- error" ~ EOF ~
           (!NEWLINE ~ ANY)* ~ EOF }
