// Copyright 2024 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_CLOCK_CONTROLLERS_CLOCKIMPL_VISITOR_TEST_DTS_CLOCK_H_
#define LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_CLOCK_CONTROLLERS_CLOCKIMPL_VISITOR_TEST_DTS_CLOCK_H_

#define CLK_ID1 12
#define CLK1_NAME "VIDEO_GATE"

#define CLK_ID2 25
#define CLK2_NAME "VIDEO_PLL"

#define CLK_ID3 32

#define CLK_ID4 43
#define CLK_ID4_RATE 2000000

#define CLK_ID5 51

#define CLK_ID6 5

#endif  // LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_CLOCK_CONTROLLERS_CLOCKIMPL_VISITOR_TEST_DTS_CLOCK_H_
