// Copyright 2023 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_GPIO_CONTROLLERS_GPIOIMPL_VISITOR_TEST_DTS_GPIO_H_
#define LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_GPIO_CONTROLLERS_GPIOIMPL_VISITOR_TEST_DTS_GPIO_H_

#define PIN1 12
#define PIN1_NAME "SOC_AUDIO_ENABLE"

#define PIN2 30
#define PIN2_NAME "SOC_AUDIO_FAULT"

#define HOG_PIN1 6
#define HOG_PIN2 8
#define HOG_PIN3 23
#define HOG_PIN2_FLAG 1
#define HOG_PIN3_FLAG 2

#define GROUP1_PIN1 3
#define GROUP1_PIN2 5
#define GROUP1_FUNCTION 4
#define GROUP1_DRIVE_STRENGTH 32

#define GROUP2_PIN1 20
#define GROUP2_PIN2 17

#define GROUP3_PIN1 7

#define GROUP4_PIN1 10

#endif  // LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_GPIO_CONTROLLERS_GPIOIMPL_VISITOR_TEST_DTS_GPIO_H_
