[fuchsia.project]
build_out_dir = { path_ref = ".build-dir" }
build_config_path = { out_dir_ref = "fuchsia_build_config.json" }
bootstrap_command = ["scripts/bootstrap.sh"]

[fuchsia.project.default_config]
repository = { default = "my-repository" }

[fuchsia.sdk]
version_check_files = [ "manifest/bazel_sdk.ensure" ]
version_check_command = ["scripts/update-sdk-and-lockfile.sh"]
